steps:
  # Build the Docker image with a unique tag based on the commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:${COMMIT_SHA}', '.']
    id: 'Build Docker Image'

  # Push the uniquely tagged image to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:${COMMIT_SHA}']
    id: 'Push Docker Image'

  # Use `kubectl set image` to directly update the deployment with the new image.
  # This command does not require a local copy of the manifest file.
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials zendesk-cluster --zone=asia-south1-c --project=affable-hydra-467019-a9
        kubectl set image deployment/zendesk-ticket-app-deployment zendesk-ticket-app=asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:${COMMIT_SHA}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=zendesk-cluster'
      - 'PROJECT_ID=affable-hydra-467019-a9'

options:
  logging: CLOUD_LOGGING_ONLY
